AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for rise-fetch-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  FetchIgUsersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Events:
        FetchIgUsers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fetch-users
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FetchIgUsersApi:
    Description: "API Gateway endpoint URL for Prod stage for FetchIgUsers function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fetch-users/"
  FetchIgUsersFunction:
    Description: "FetchIgUsers Lambda Function ARN"
    Value: !GetAtt FetchIgUsersFunction.Arn
  FetchIgUsersFunctionIamRole:
    Description: "Implicit IAM Role created for FetchIgUsers function"
    Value: !GetAtt FetchIgUsersFunction.Arn
